<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Order
 *
 * @package App\Entity
 */
#[ORM\Table(name: "orders")]
#[ORM\Entity(repositoryClass: OrderRepository::class)]
class Order
{
    /**
     * @var integer|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        type: 'integer',
        unique: true,
        nullable: false,
        updatable: false,
        options: ['unsigned' => true],
        columnDefinition: 'smallserial', // autogenerated id: serial [1 ... 32'767]
        generated: 'INSERT'
    )]
    private int|null $id = null {
        get {
            return $this->id;
        }
    }

    /**
     * @var Shop
     */
    #[ORM\ManyToOne(targetEntity: Shop::class, cascade: ['persist'], inversedBy: 'telegramIntegrations')]
    private Shop $shop;

    /** @var string */
    #[ORM\Column(type: Types::STRING, length: 64, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private string $number;

    /** @var integer */
    #[ORM\Column(type: Types::INTEGER, unique: false, nullable: false, updatable: false, options: ['unsigned' => true], columnDefinition: 'integer')]
    private int $total;

    /** @var string */
    #[ORM\Column(type: Types::STRING, length: 64, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private string $customerName;

    /**
     * @var DateTimeInterface
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, unique: false, nullable: false, updatable: false)]
    private DateTimeInterface $createdAt;

    /**
     * @var Collection<int, Shop>
     */
    #[ORM\OneToMany(targetEntity: TelegramSendLog::class, mappedBy: 'order', cascade: ['persist'])]
    private Collection $telegramSendLog;

    /**
     * Order constructor.
     *
     * @param Shop $shop
     * @param string $number
     * @param int $total
     * @param string $customerName
     * @param DateTimeInterface|null $dt
     */
    public function __construct(
        Shop $shop, string $number, int $total, string $customerName, ?DateTimeInterface $dt = null)
    {
        $this->shop = $shop;
        $this->number = $number;
        $this->customerName = $customerName;
        $this->total = $total;
        $this->createdAt = $dt ?? new DateTime();
        $this->telegramSendLog = new ArrayCollection();
    }

    /**
     * @returns integer|null
     */
    public function getId(): int|null
    {
        return $this->id;
    }

    /**
     * @return Shop
     */
    public function getShop(): Shop
    {
        return $this->shop;
    }

    /**
     * @return $this
     */
    public function setShop(Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    /**
     * @return string
     */
    public function getNumber(): string
    {
        return $this->number;
    }

    /**
     * @param string $number
     * @return $this
     */
    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return int
     */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * @param int $total
     * @return $this
     */
    public function setTotal(int $total): self
    {
        $this->total = $total;

        return $this;
    }

    /**
     * @return string
     */
    public function getCustomerName(): string
    {
        return $this->customerName;
    }

    /**
     * @param string $customerName
     * @return $this
     */
    public function setCustomerName(string $customerName): self
    {
        $this->customerName = $customerName;

        return $this;
    }

    /**
     * @return DateTimeInterface
     */
    public function getCreatedAt(): DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @returns Collection<int, TelegramSendLog>
     */
    public function getTelegramSendLog(): Collection
    {
        return $this->telegramSendLog;
    }

    /**
     * @return array<string, int|string>
     */
    public function display(): array
    {
        return [
            'id' => $this->id,
            'shop' => $this->shop->display(),
            'number' => $this->number,
            'total' => $this->total,
            'customerName' => $this->customerName,
            'createdAt' => $this->createdAt->format('Y-m-d H:i:s'),
        ];
    }
}
