<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\ShopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Shop
 *
 * @package App\Entity
 */
#[ORM\Table(name: "shops")]
#[ORM\Entity(repositoryClass: ShopRepository::class)]
class Shop
{
    /**
     * @var integer|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        type: 'integer',
        unique: true,
        nullable: false,
        updatable: false,
        options: ['unsigned' => true],
        columnDefinition: 'smallserial', // autogenerated id: serial [1 ... 32'767]
        generated: 'INSERT'
    )]
    private int|null $id = null {
        get {
            return $this->id;
        }
    }

    /**
     * @var string
     */
    #[ORM\Column(type: Types::STRING, length: 256, unique: false, nullable: false, options: ['fixed' => false])]
    private string $name;

    /**
     * @var Collection<int, Shop>
     */
    #[ORM\OneToMany(targetEntity: Shop::class, mappedBy: 'shop', cascade: ['persist'])]
    private Collection $telegramIntegrations;

    /**
     * @var Collection<int, Shop>
     */
    #[ORM\OneToMany(targetEntity: TelegramSendLog::class, mappedBy: 'shop', cascade: ['persist'])]
    private Collection $telegramSendLog;

    /**
     * Name constructor.
     *
     * @param string $name
     */
    public function __construct(string $name)
    {
        $this->name = $name;
        $this->telegramIntegrations = new ArrayCollection();
        $this->telegramSendLog = new ArrayCollection();
    }

    /**
     * @returns integer|null
     */
    public function getId(): int|null
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @returns Collection<int, TelegramIntegration>
     */
    public function getTelegramIntegrations(): Collection
    {
        return $this->telegramIntegrations;
    }

    /**
     * @returns Collection<int, TelegramSendLog>
     */
    public function getTelegramSendLog(): Collection
    {
        return $this->telegramSendLog;
    }

    /**
     * @return array<string, int|string>
     */
    public function display(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
        ];
    }
}
