<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\TelegramSendLogStatusEnum;
use App\Repository\TelegramSendLogRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class TelegramSendLog
 *
 * @package App\Entity
 */
#[ORM\Entity(repositoryClass: TelegramSendLogRepository::class)]
#[ORM\UniqueConstraint('UX_TELEGRAM_SEND_LOG_SHOP_ORDER', ['shop_id', 'order_id'])]
class TelegramSendLog
{
    /**
     * @var integer|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        type: 'integer',
        unique: true,
        nullable: false,
        updatable: false,
        options: ['unsigned' => true],
        columnDefinition: 'smallserial', // autogenerated id: serial [1 ... 32'767]
        generated: 'INSERT'
    )]
    private int|null $id = null {
        get {
            return $this->id;
        }
    }

    /**
     * @var Shop
     */
    #[ORM\ManyToOne(targetEntity: Shop::class, cascade: ['persist'], inversedBy: 'telegramSendLog')]
    private Shop $shop;

    /**
     * @var Order
     */
    #[ORM\ManyToOne(targetEntity: Order::class, cascade: ['persist'], inversedBy: 'telegramSendLog')]
    private Order $order;

    /** @var string */
    #[ORM\Column(type: Types::STRING, length: 2056, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private string $message;

    /** @var TelegramSendLogStatusEnum */
    #[ORM\Column(type: Types::ENUM, length: 16, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private TelegramSendLogStatusEnum $status;

    /** @var string */
    #[ORM\Column(type: Types::STRING, length: 512, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private string $error;

    /**
     * @var DateTimeInterface
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, unique: false, nullable: false, updatable: false)]
    private DateTimeInterface $sentAt;

    /**
     * TelegramIntegration constructor.
     *
     * @param Shop $shop
     * @param Order $order
     * @param string $message
     * @param TelegramSendLogStatusEnum $status
     * @param string $error
     * @param DateTimeInterface|null $dt
     */
    public function __construct(
        Shop               $shop, Order $order, string $message, TelegramSendLogStatusEnum $status, string $error = '',
        ?DateTimeInterface $dt = null
    )
    {
        $this->shop = $shop;
        $this->order = $order;
        $this->message = $message;
        $this->status = $status;
        $this->error = $error;
        $this->sentAt = $dt ?? new DateTime();
    }

    /**
     * @returns integer|null
     */
    public function getId(): int|null
    {
        return $this->id;
    }

    /**
     * @return Shop
     */
    public function getShop(): Shop
    {
        return $this->shop;
    }

    /**
     * @return $this
     */
    public function setShop(Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    /**
     * @return Order
     */
    public function getOrder(): Order
    {
        return $this->order;
    }

    /**
     * @return $this
     */
    public function setOrder(Order $order): self
    {
        $this->order = $order;

        return $this;
    }

    /**
     * @return string
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * @param string $message
     * @return $this
     */
    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return TelegramSendLogStatusEnum
     */
    public function getStatus(): TelegramSendLogStatusEnum
    {
        return $this->status;
    }

    /**
     * @param TelegramSendLogStatusEnum $status
     * @return $this
     */
    public function setStatus(TelegramSendLogStatusEnum $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string
     */
    public function getError(): string
    {
        return $this->error;
    }

    /**
     * @param string $error
     * @return $this
     */
    public function setError(string $error = ''): self
    {
        $this->error = $error;

        return $this;
    }

    /**
     * @return DateTimeInterface
     */
    public function getSentAt(): DateTimeInterface
    {
        return $this->sentAt;
    }

    /**
     * @return array<string, int|string>
     */
    public function display(): array
    {
        return [
            'id' => $this->id,
            'shop' => $this->shop->display(),
            'order' => $this->order->display(),
            'status' => $this->status->value,
            'message' => $this->message,
            'error' => $this->error,
            'sentAt' => $this->sentAt->format('Y-m-d H:i:s'),
        ];
    }
}
