<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\TelegramIntegrationRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class TelegramIntegration
 *
 * @package App\Entity
 */
#[ORM\Table(name: "telegram_integrations")]
#[ORM\Entity(repositoryClass: TelegramIntegrationRepository::class)]
#[ORM\UniqueConstraint('UX_TELEGRAM_INTEGRATIONS_SHOP', ['shop_id'])]
class TelegramIntegration
{
    /**
     * @var integer|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(
        type: 'integer',
        unique: true,
        nullable: false,
        updatable: false,
        options: ['unsigned' => true],
        columnDefinition: 'smallserial', // autogenerated id: serial [1 ... 32'767]
        generated: 'INSERT'
    )]
    private int|null $id = null {
        get {
            return $this->id;
        }
    }

    /**
     * @var Shop
     */
    #[ORM\ManyToOne(targetEntity: Shop::class, cascade: ['persist'], inversedBy: 'telegramIntegrations')]
    private Shop $shop;

    /** @var string */
    #[ORM\Column(type: Types::STRING, length: 256, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private string $botToken;

    /** @var string */
    #[ORM\Column(type: Types::STRING, length: 32, unique: false, nullable: false, updatable: true, options: ['fixed' => false])]
    private string $chatId;

    /** @var bool */
    #[ORM\Column(type: Types::BOOLEAN, nullable: false, updatable: true)]
    private bool $enabled;

    /**
     * @var DateTimeInterface
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, unique: false, nullable: false, updatable: false)]
    private DateTimeInterface $createdAt;

    /**
     * @var DateTimeInterface
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, unique: false, nullable: false, updatable: true)]
    private DateTimeInterface $updatedAt;

    /**
     * TelegramIntegration constructor.
     *
     * @param Shop $shop
     * @param string $botToken
     * @param string $chatId
     * @param bool $enabled
     * @param DateTimeInterface|null $dt
     */
    public function __construct(Shop $shop, string $botToken, string $chatId, bool $enabled, ?DateTimeInterface $dt = null
    )
    {
        $this->shop = $shop;
        $this->botToken = $botToken;
        $this->chatId = $chatId;
        $this->enabled = $enabled;
        $this->createdAt = $dt ?? new DateTime();
        $this->updatedAt = $dt ?? $this->createdAt;
    }

    /**
     * @returns integer|null
     */
    public function getId(): int|null
    {
        return $this->id;
    }

    /**
     * @return Shop
     */
    public function getShop(): Shop
    {
        return $this->shop;
    }

    /**
     * @return $this
     */
    public function setShop(Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    /**
     * @return string
     */
    public function getBotToken(): string
    {
        return $this->botToken;
    }

    /**
     * @param string $botToken
     * @return $this
     */
    public function setBotToken(string $botToken): self
    {
        $this->botToken = $botToken;

        return $this;
    }

    /**
     * @return string
     */
    public function getChatId(): string
    {
        return $this->chatId;
    }

    /**
     * @param string $chatId
     * @return $this
     */
    public function setChatId(string $chatId): self
    {
        $this->chatId = $chatId;

        return $this;
    }

    /**
     * @return bool
     */
    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     * @return $this
     */
    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * @return DateTimeInterface
     */
    public function getCreatedAt(): DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @return DateTimeInterface
     */
    public function getUpdatedAt(): DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @param DateTimeInterface $updatedAt
     * @return $this
     */
    public function setUpdatedAt(DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return array<string, int|string>
     */
    public function display(): array
    {
        return [
            'id' => $this->id,
            'shop' => $this->shop->display(),
            'botToken' => $this->botToken,
            'chatId' => $this->chatId,
            'enabled' => $this->enabled ? 'Y' : 'F',
            'createdAt' => $this->createdAt->format('Y-m-d H:i:s'),
            'updatedAt' => $this->updatedAt->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * @return array<string, int|string>
     */
    public function displaySafe(): array
    {
        return [
            'id' => $this->id,
            'shop' => $this->shop->display(),
            'botToken' => '{{MASKED}}',
            'chatId' => $this->chatId,
            'enabled' => $this->enabled,
            'createdAt' => $this->createdAt->format('Y-m-d H:i:s'),
            'updatedAt' => $this->updatedAt->format('Y-m-d H:i:s'),
        ];
    }
}
