server {
    listen 443 ssl;
    server_name _;
    error_log  /var/log/nginx/posiflora-error.log;
    access_log  /var/log/nginx/posiflora-access.log;

    client_max_body_size 2000M;
    charset utf-8;

    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    root /var/www/html;
    index index.html;

    location / { try_files $uri /index.php$is_args$query_string; }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ ^/index\.php(/|$) {
        # fastcgi_pass http://host.docker.internal:4401;
        fastcgi_pass posiflora-apps:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
