<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408080249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE telegram_integrations_shop_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE orders_shop_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE telegram_send_log_shop_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE telegram_send_log_order_id_seq CASCADE');
        $this->addSql('ALTER TABLE orders ALTER id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE orders ALTER total SET NOT NULL');
        $this->addSql('ALTER TABLE orders ALTER shop_id TYPE INT');
        $this->addSql('ALTER TABLE orders ALTER shop_id DROP DEFAULT');
        $this->addSql('ALTER TABLE orders ALTER shop_id DROP NOT NULL');
        $this->addSql('ALTER INDEX idx_002 RENAME TO IDX_E52FFDEE4D16C4DD');
        $this->addSql('ALTER TABLE shops ALTER id TYPE INT');
        $this->addSql('ALTER TABLE shops ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE shops ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX idx_001');
        $this->addSql('ALTER TABLE telegram_integrations ALTER id TYPE INT');
        $this->addSql('ALTER TABLE telegram_integrations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE telegram_integrations ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE telegram_integrations ALTER shop_id TYPE INT');
        $this->addSql('ALTER TABLE telegram_integrations ALTER shop_id DROP DEFAULT');
        $this->addSql('ALTER TABLE telegram_integrations ALTER shop_id DROP NOT NULL');
        $this->addSql('ALTER INDEX ux_telegram_integrations_shop RENAME TO telegram_integrations_shop');
        $this->addSql('ALTER TABLE telegram_send_log ALTER id TYPE INT');
        $this->addSql('ALTER TABLE telegram_send_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE telegram_send_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE telegram_send_log ALTER shop_id TYPE INT');
        $this->addSql('ALTER TABLE telegram_send_log ALTER shop_id DROP DEFAULT');
        $this->addSql('ALTER TABLE telegram_send_log ALTER shop_id DROP NOT NULL');
        $this->addSql('ALTER TABLE telegram_send_log ALTER order_id TYPE INT');
        $this->addSql('ALTER TABLE telegram_send_log ALTER order_id DROP DEFAULT');
        $this->addSql('ALTER TABLE telegram_send_log ALTER order_id DROP NOT NULL');
        $this->addSql('ALTER INDEX idx_003 RENAME TO IDX_77AA2A944D16C4DD');
        $this->addSql('ALTER INDEX idx_004 RENAME TO IDX_77AA2A948D9F6D38');
        $this->addSql('ALTER INDEX ux_telegram_send_log_shop_order RENAME TO telegram_send_log_shop_order');
    }

    public function down(Schema $schema): void
    {

    }
}
